apiVersion: v1
kind: Service
metadata:
  name: job-portal-api-user-service
spec:
  selector:
    app: job-portal-api-user-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort
  