apiVersion: v1
kind: Service
metadata:
  name: job-portal-api-feeds-service
  namespace: pd-job-portal
spec:
  selector:
    app: job-portal-api-feeds
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30009
  type: LoadBalancer
  
