apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-api-feeds
  namespace: pd-job-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-portal-api-feeds #This should be same label
  template:
    metadata:
      labels:
        app: job-portal-api-feeds #This should be same label
    spec:
      containers:
        - name: job-portal-api-feeds
          image: pdesaidocker/pd-job-portal-api-feeds:v4
          ports:
            - containerPort: 8081 #port defined in image dockerfile
          env:
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: job-portal-configmap
                  key: CORS_ALLOWED_ORIGINS
